INSERT INTO CUSTOMERS
    (ID, NAME, DOCUMENT, EMAIL, AVAILABLE_VALUE)
SELECT 1, 'Joaquim Ferreira', '27242216052', 'joaquim.ferreira@gmail.com', 5000
WHERE
    NOT EXISTS (
        SELECT ID FROM CUSTOMERS WHERE ID = 1
    );

INSERT INTO CUSTOMERS
    (ID, NAME, DOCUMENT, EMAIL, AVAILABLE_VALUE)
SELECT 2, 'João Nunes', '66164520002', 'joao.nunes@gmail.com', 10000
WHERE
    NOT EXISTS (
        SELECT ID FROM CUSTOMERS WHERE ID = 2
    );

INSERT INTO CUSTOMERS
    (ID, NAME, DOCUMENT, EMAIL, AVAILABLE_VALUE)
SELECT 3, 'Maria Silva', '50683772015', 'maria.silva@gmail.com', 20000
WHERE
    NOT EXISTS (
        SELECT ID FROM CUSTOMERS WHERE ID = 3
    );